# Generated by Django 3.1.4 on 2020-12-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0005_delete_place_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('organization_number', models.IntegerField()),
                ('qrcode', models.IntegerField()),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('reminder_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Alarm System', 'Alarm System'), ('Locking System', 'Locking System'), ('Door automation', 'Door automation'), ('Dim generator', 'Dim generator'), ('Backup battery', 'Backup battery')], max_length=50)),
                ('pin_color', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Geoinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateTimeField()),
                ('next_service_date', models.DateTimeField()),
                ('place', models.TextField()),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.service_type')),
            ],
        ),
    ]
