# Generated by Django 3.1.4 on 2020-12-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20201228_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='geoinfo',
            old_name='place',
            new_name='service_installation_place',
        ),
        migrations.AlterField(
            model_name='service_type',
            name='pin_color',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black'), ('Purple', 'Purple'), ('Orange', 'Orange')], max_length=10),
        ),
    ]
