# Generated by Django 3.1.4 on 2020-12-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_geoinfo_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_type',
            name='pin_color',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Dark Purple', 'Dark Purple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='system_name',
            field=models.CharField(choices=[('Purple', 'Alarm System'), ('Blue', 'Locking System'), ('Dark Purple', 'Door automation'), ('Black', 'Dim generator'), ('Green', 'Backup battery'), ('Orange', 'Access control system')], max_length=50),
        ),
    ]
