# Generated by Django 3.0.3 on 2020-12-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20201228_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_type',
            name='customer',
        ),
        migrations.AddField(
            model_name='geoinfo',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.CustomerInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_type',
            name='pin_color',
            field=models.CharField(choices=[('#2eff00', 'Green'), ('#02baff', 'Blue'), ('#000000', 'Black'), ('#b36ae2', 'Purple'), ('#ff9c34', 'Orange'), ('#8000ff', 'Dark Purple')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='system_name',
            field=models.CharField(choices=[('Alarm System', 'Alarm System'), ('Locking System', 'Locking System'), ('Door automation', 'Door automation'), ('Dim generator', 'Dim generator'), ('Backup battery', 'Backup battery'), ('Access control system', 'Access control system')], max_length=50),
        ),
    ]
