# Generated by Django 3.1.2 on 2020-12-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20201229_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoinfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.DeleteModel(
            name='Geoinfo',
        ),
        migrations.DeleteModel(
            name='Service_type',
        ),
    ]
