# Generated by Django 3.1.2 on 2020-12-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0015_auto_20201230_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=128)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_address', models.TextField()),
                ('organization_number', models.IntegerField()),
                ('qr_code', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lang', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50)),
                ('pin_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateTimeField()),
                ('next_service_date', models.DateTimeField()),
                ('reminder', models.BooleanField(default=False)),
                ('reminder_email', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.customerinfo')),
                ('service_installation_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.place')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.service_type')),
            ],
        ),
    ]
