# Generated by Django 3.1.2 on 2021-01-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_customerinfo_place_reminder_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder',
            new_name='is_remind',
        ),
    ]
