# Generated by Django 3.1.2 on 2021-01-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_reminder_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
